# Generated by Django 3.2.7 on 2024-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderack', '0008_auto_20220804_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderacknowledgement',
            name='PI_BasicValuePercentage',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='orderacknowledgement',
            name='PI_GstPercentage',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
